Traceback (most recent call last):
  File "/Users/chayne/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/chayne/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/chayne/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/chayne/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/chayne/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/chayne/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/chayne/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/chayne/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
median_gr = (alt.Chart(df.iloc[:,3:].reset_index())
               .mark_bar()
               .encode(x=alt.X('D:Q',title='median'),
                       y=alt.Y('index:O',title='row')))
median_gr
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/fr/47109l7d71vgx77b578ll3f80000gn/T/ipykernel_19455/3258535833.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m median_gr = (alt.Chart(df.iloc[:,3:].reset_index())
[0m[1;32m      2[0m                [0;34m.[0m[0mmark_bar[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m                .encode(x=alt.X('D:Q',title='median'),
[1;32m      4[0m                        y=alt.Y('index:O',title='row')))
[1;32m      5[0m [0mmedian_gr[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'alt' is not defined
NameError: name 'alt' is not defined

